# Linear Algebra
Week 2 assignment : https://d2l.ai/chapter_preliminaries/linear-algebra.html#scalars

## 2.3.1 Scalars

In [3]:
from mxnet import np, npx # import libraries 
npx.set_np()    # Setting NumPy shape and array semantics at the same time.

# giving x and y values
x = np.array(4.57)
y = np.array(3.78)

# operations
x + y, x * y, x / y, x ** y

(array(8.35), array(17.274601), array(1.2089947), array(312.2362))

## 2.3.2 Vectors

In [3]:
# make an array x of 12 elements
x = np.arange(12)
x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [4]:
# access the 5th element of the array
x[5]

array(5.)

### 2.3.2.1 Length, Dimensionality, and Shape

In [5]:
# access the length of the array
len(x)

12

In [8]:
# shape of the array
x.shape

(12,)

## 2.3.3 Matrices

In [9]:
# make a matrix A of 75 elements, shape 25x3
A = np.arange(75).reshape(25, 3)
A

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.],
       [24., 25., 26.],
       [27., 28., 29.],
       [30., 31., 32.],
       [33., 34., 35.],
       [36., 37., 38.],
       [39., 40., 41.],
       [42., 43., 44.],
       [45., 46., 47.],
       [48., 49., 50.],
       [51., 52., 53.],
       [54., 55., 56.],
       [57., 58., 59.],
       [60., 61., 62.],
       [63., 64., 65.],
       [66., 67., 68.],
       [69., 70., 71.],
       [72., 73., 74.]])

In [10]:
# Matrix transpose
A.T

array([[ 0.,  3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30., 33., 36.,
        39., 42., 45., 48., 51., 54., 57., 60., 63., 66., 69., 72.],
       [ 1.,  4.,  7., 10., 13., 16., 19., 22., 25., 28., 31., 34., 37.,
        40., 43., 46., 49., 52., 55., 58., 61., 64., 67., 70., 73.],
       [ 2.,  5.,  8., 11., 14., 17., 20., 23., 26., 29., 32., 35., 38.,
        41., 44., 47., 50., 53., 56., 59., 62., 65., 68., 71., 74.]])

In [16]:
# symmetric matrix is equal to its transpose
B = np.array([[33, 23, 55], [23, 10, 0], [55, 0, 95]])
B

array([[33., 23., 55.],
       [23., 10.,  0.],
       [55.,  0., 95.]])

In [18]:
B == B.T

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## 2.3.4 Tensors

In [23]:
# Tensors
X = np.arange(32).reshape(2, 8, 2)
X

array([[[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.],
        [ 6.,  7.],
        [ 8.,  9.],
        [10., 11.],
        [12., 13.],
        [14., 15.]],

       [[16., 17.],
        [18., 19.],
        [20., 21.],
        [22., 23.],
        [24., 25.],
        [26., 27.],
        [28., 29.],
        [30., 31.]]])

## 2.3.5 Basic properties of tensor arithmetic

In [27]:
A = np.arange(28).reshape(7, 4)
B = A.copy()  # Assign a copy of A to B by allocating new memory
A, A + B

(array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.],
        [20., 21., 22., 23.],
        [24., 25., 26., 27.]]),
 array([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.],
        [40., 42., 44., 46.],
        [48., 50., 52., 54.]]))

In [28]:
A * B # multiplying tensors

array([[  0.,   1.,   4.,   9.],
       [ 16.,  25.,  36.,  49.],
       [ 64.,  81., 100., 121.],
       [144., 169., 196., 225.],
       [256., 289., 324., 361.],
       [400., 441., 484., 529.],
       [576., 625., 676., 729.]])

In [29]:
a = 4
X = np.arange(32).reshape(2, 8, 2)
a + X, (a * X).shape # multiplying and adding tensors

(array([[[ 4.,  5.],
         [ 6.,  7.],
         [ 8.,  9.],
         [10., 11.],
         [12., 13.],
         [14., 15.],
         [16., 17.],
         [18., 19.]],
 
        [[20., 21.],
         [22., 23.],
         [24., 25.],
         [26., 27.],
         [28., 29.],
         [30., 31.],
         [32., 33.],
         [34., 35.]]]),
 (2, 8, 2))

## 2.3.6 Reduction

In [30]:
# Reduction
x = np.arange(12)
x, x.sum() # sum function

(array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]),
 array(66.))

In [31]:
A.shape, A.sum() # sum of A

((7, 4), array(378.))

In [32]:
A_sum_axis0 = A.sum(axis=0) # reducing row dim 
A_sum_axis0, A_sum_axis0.shape # sums up elements of all the rows

(array([ 84.,  91.,  98., 105.]), (4,))

In [33]:
A_sum_axis1 = A.sum(axis=1) # reducing column dim by summing up elements of all columns
A_sum_axis1, A_sum_axis1.shape

(array([  6.,  22.,  38.,  54.,  70.,  86., 102.]), (7,))

In [34]:
A.sum(axis=[0, 1])  # Same as A.sum()

array(378.)

In [35]:
A.mean(), A.sum() / A.size # those two operations are equivalent, as the mean is calculated by the sum divided by the size

(array(13.5), array(13.5))

In [36]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0] # Can reduce dim along a given axis

(array([12., 13., 14., 15.]), array([12., 13., 14., 15.]))

### 2.3.6.1 Non-Reduction Sum

In [37]:
#Non-Reduction Sum
sum_A = A.sum(axis=1, keepdims=True) # doesn't change the dimension of axis
sum_A

array([[  6.],
       [ 22.],
       [ 38.],
       [ 54.],
       [ 70.],
       [ 86.],
       [102.]])

In [38]:
A / sum_A # broadcasting

array([[0.        , 0.16666667, 0.33333334, 0.5       ],
       [0.18181819, 0.22727273, 0.27272728, 0.3181818 ],
       [0.21052632, 0.23684211, 0.2631579 , 0.28947368],
       [0.22222222, 0.24074075, 0.25925925, 0.2777778 ],
       [0.22857143, 0.24285714, 0.25714287, 0.27142859],
       [0.23255815, 0.24418604, 0.25581396, 0.26744187],
       [0.23529412, 0.24509804, 0.25490198, 0.2647059 ]])

In [39]:
A.cumsum(axis=0) # calculates the sum of elements of A along the 0 axis (row by row) 

array([[  0.,   1.,   2.,   3.],
       [  4.,   6.,   8.,  10.],
       [ 12.,  15.,  18.,  21.],
       [ 24.,  28.,  32.,  36.],
       [ 40.,  45.,  50.,  55.],
       [ 60.,  66.,  72.,  78.],
       [ 84.,  91.,  98., 105.]])

## 2.3.7 Dot products

In [42]:
#Dot products
y = np.ones(12)
x, y, np.dot(x, y) # sum over the products of the elements at the same position

(array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array(66.))

In [43]:
np.sum(x * y) # equivalent operation

array(66.)

## 2.3.8 Matrix-vector products

In [45]:
#Mqtrix-vector product
A = np.arange(12)
A.shape, x.shape, np.dot(A, x)

((12,), (12,), array(506.))

## 2.3.9 Matrix-matrix multiplication

In [49]:
# Matrix-matrix multiplication
B = np.ones(shape=(6, 2))
A = A.reshape(2, 6)
np.dot(A, B)

array([[15., 15.],
       [51., 51.]])

## 2.3.10 Norms

In [51]:
#Norms
u = np.array([2, -6])
np.linalg.norm(u)

array(6.3245554)

In [52]:
np.abs(u).sum() # absolute value

array(8.)

In [55]:
np.linalg.norm(np.ones((3, 19))) # Frobenius norm

array(7.5498343)

## 2.3.13 Exercises

### 1. Prove that the transpose of a matrix  A ’s transpose is  A :  (A⊤)⊤=A .

In [8]:
A = np.array([[33, 23, 55], [23, 10, 0], [55, 0, 95]])
A

array([[33., 23., 55.],
       [23., 10.,  0.],
       [55.,  0., 95.]])

In [9]:
A == A.T

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 2. Given two matrices  A  and  B , show that the sum of transposes is equal to the transpose of a sum:  A⊤+B⊤=(A+B)⊤

In [11]:
A = np.array([[33, 23, 55], [23, 10, 0], [55, 0, 95]])
A

array([[33., 23., 55.],
       [23., 10.,  0.],
       [55.,  0., 95.]])

In [12]:
B = np.array([[55, 23, 33], [10, 23, 0], [0, 55, 95]])
B

array([[55., 23., 33.],
       [10., 23.,  0.],
       [ 0., 55., 95.]])

In [13]:
(A.T)+(B.T) 

array([[ 88.,  33.,  55.],
       [ 46.,  33.,  55.],
       [ 88.,   0., 190.]])

In [14]:
(A+B).T

array([[ 88.,  33.,  55.],
       [ 46.,  33.,  55.],
       [ 88.,   0., 190.]])

In [15]:
(A+B).T == (A.T)+(B.T)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 3.Given any square matrix  A , is  A+A⊤  always symmetric? Why?

In [21]:
A = np.arange(16).reshape(4,4)
A

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [24]:
A.T

array([[ 0.,  4.,  8., 12.],
       [ 1.,  5.,  9., 13.],
       [ 2.,  6., 10., 14.],
       [ 3.,  7., 11., 15.]])

In [22]:
A + A.T

array([[ 0.,  5., 10., 15.],
       [ 5., 10., 15., 20.],
       [10., 15., 20., 25.],
       [15., 20., 25., 30.]])

In [23]:
A == A.T # not symmetric because A is not equal to its transpose.

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### 4. We defined the tensor X of shape ( 2 ,  3 ,  4 ) in this section. What is the output of len(X)?

In [27]:
X = np.arange(24).reshape(2, 3, 4)
X

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]],

       [[12., 13., 14., 15.],
        [16., 17., 18., 19.],
        [20., 21., 22., 23.]]])

In [28]:
len(X)

2

### 5. For a tensor X of arbitrary shape, does len(X) always correspond to the length of a certain axis of X? What is that axis?

In [26]:
X.shape # len(X) corresponds to the length of the first axis of X

(2, 3, 4)

### 6. Run A / A.sum(axis=1) and see what happens. Can you analyze the reason?

In [29]:
A / A.sum(axis=1)

array([[0.        , 0.04545455, 0.05263158, 0.05555556],
       [0.6666667 , 0.22727273, 0.15789473, 0.12962963],
       [1.3333334 , 0.4090909 , 0.2631579 , 0.2037037 ],
       [2.        , 0.59090906, 0.36842105, 0.2777778 ]])

In [30]:
A # column dimension has been reduced by summing up elements of all columns

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

### 7. When traveling between two points in Manhattan, what is the distance that you need to cover in terms of the coordinates, i.e., in terms of avenues and streets? Can you travel diagonally?

You can travel diagonally if you're a bird but humans need to stick to avenues and streets with coordinates, for example if point A is at (0, 0) and you travel to point B at (3, 4) one would have to go first to (0, 4) or (3, 0) and then point B. Going through middle points (0, 1), (1,1) etc is also an option.

### 8. Consider a tensor with shape ( 2 ,  3 ,  4 ). What are the shapes of the summation outputs along axis  0 ,  1 , and  2 ?

In [32]:
X = np.arange(24).reshape(2, 3, 4)

In [33]:
X.sum(axis=0)

array([[12., 14., 16., 18.],
       [20., 22., 24., 26.],
       [28., 30., 32., 34.]])

In [38]:
X.sum(axis=1)

array([[12., 15., 18., 21.],
       [48., 51., 54., 57.]])

In [39]:
X.sum(axis=2)

array([[ 6., 22., 38.],
       [54., 70., 86.]])

### 9. Feed a tensor with 3 or more axes to the linalg.norm function and observe its output. What does this function compute for ndarrays of arbitrary shape?

In [43]:
X = np.arange(90).reshape(3, 10, 3)

In [44]:
np.linalg.norm(X) # maps a vector to a scalar  --> square root of the sum of the squares of the vector elements

array(488.84045)